name: libavcodec58-core22
version: '4.4.2'
summary: FFmpeg library with de/encoders for audio/video codecs - runtime files
description: |
  Use the content interface to access libavcodec library  
  https://snapcraft.io/docs/content-interface

base: core22
confinement: strict

slots:
  libavcodec58-core22:
    interface: content
    read:
    - /lib

parts:
  libavcodec:
    plugin: nil
    stage-packages:
    - libavcodec58
    organize:
      usr/lib/**/*.so*: lib/
    prime:
    - lib/libavcodec.*
    - lib/libaom.*
    - lib/libavutil.*
    - lib/libOpenCL.*  # libavutil
    - lib/libvdpau.*  # libavutil
    - lib/libcodec2.*
    - lib/libdav1d.*
    - lib/libgsm.*
    - lib/libmfx.*
    - lib/libshine.*
    - lib/libsnappy.*
    - lib/libswresample.*
    - lib/libsoxr.*  # libswresample
    - lib/libx264.*
    - lib/libx265.*
    - lib/libnuma.*  # libx265
    - lib/libxvidcore.*
    - lib/libzvbi.*
